# Generated by Django 4.2.13 on 2024-06-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_alter_expenseitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_budget', models.FloatField(blank=True, default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.expenselog'),
        ),
    ]
