# Generated by Django 4.2.13 on 2024-06-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_expenseitem_amount_expenselog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselog',
            name='log_name',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
