# Generated by Django 4.2.13 on 2024-06-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_expenselog_log_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='expense_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.expenselog'),
        ),
        migrations.AlterField(
            model_name='expenselog',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
