# Generated by Django 4.2.13 on 2024-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_expenseitem_expense_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='expenselog',
            name='log_name',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Log Name'),
        ),
    ]
